config/routes.rb
Rails.application.routes.draw do
 
  get 'samples/new'

  get 'samples/edit'

  get 'drill_logs/new'

  get 'drill_logs/create'

  get 'drill_logs/destroy'

 # resources :holes

 resources :holes do
    resources :drill_logs, only: [:new, :create]
    resources :samples , only: [:new, :create]
  end

 root to: 'holes#index'
 
end

app/models/drill_log.rb
class DrillLog < ActiveRecord::Base
  belongs_to :hole

  validates :hole_id,
        presence: true

  validates :from,
        numericality: { only_integer: true }

  validates :to,
        numericality: { only_integer: true }

  validates :num_pails,
        numericality: { only_integer: true }

  validates :rock_type,
        presence: true

  drill = "#{Rails.root}/public/DrillDataMay13.csv"

  def self.import(file)
    CSV.foreach(file) do |p|
      from = p[5].to_i
      to = p[6].to_i
      pails = p[8].to_i
      hole = p[0]
      theHole = Hole.where( ID: hole )
      hole_id = theHole[0].id
      if p[9]
        test = DrillLog.new(hole_id: hole_id, from: from, to: to, num_pails: pails, rock_type: p[9])
        puts test.hole_id
        puts test.from
        puts test.to
        puts test.rock_type
        puts "New entry!"
        test.save!
      end
    end
  end
end

app/models/hole.rb
class Hole < ActiveRecord::Base

  has_many :drill_logs, dependent: :destroy 
  has_many :samples, dependent: :destroy 

   
  validates :ID,
    presence: true

  # validates :date,
  #   presence: true

  validates :lat, numericality: {greater_than_or_equal_to: -90,  \
  less_than_or_equal_to: 90 }
 
 validates :lng, numericality: { greater_than_or_equal_to: -180,  \
  less_than_or_equal_to: 180 }

  drill = "#{Rails.root}/public/DrillDataMay13.csv"
  
  drill = "/media/ng/DATA/GIS/HayesCreek2016/DrillData/DrillDataMay17.csv"

  def self.import(file)
    CSV.foreach(file) do |p|
      lat = p[3].to_f
      lng = p[4].to_f
      hole = p[0]
      theHole = Hole.exists?( ID: hole )
      puts hole
      puts theHole
      unless theHole
        test = Hole.new(ID: p[0], date: p[2], lat: lat, lng: lng)
        puts test.ID
        puts test.date
        puts test.lat
        puts test.lng
        puts "New entry!"
        test.save!
      end
    end
  end
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  belongs_to :hole

  validates :hole,
        presence: true

  validates :from,
        numericality: { only_integer: true }

  validates :to,
        numericality: { only_integer: true }

  validates :rock_type,
        presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drill_logs_controller.rb
class DrillLogsController < ApplicationController

  before_filter :load_hole

  def new
    # @hole = Hole.find(params[:hole_id])
    @drill_log = @hole.drill_logs.build
  end

  def create
    # @hole = Hole.find(params[:hole_id])
    @drill_log = @hole.drill_logs.build(drill_log_params)

    if @drill_log.save
      redirect_to @hole, notice: "Drill Log created successfully"
    else
      render :new
    end
  end

  def destroy
  end

  protected

  def load_hole
    @hole = Hole.find(params[:hole_id])
  end

  def drill_log_params
    params.require(:drill_log).permit(:from, :to, :num_pails, :rock_type)
  end
end

app/controllers/holes_controller.rb
class HolesController < ApplicationController


      respond_to :html, :json

      def index
        @holes = Hole.all
        @geojson = Array.new

        @holes.each do |hole|
          @geojson << {
            type: 'Feature',
            geometry: {
              type: 'Point',
              coordinates: [hole.lng, hole.lat]
            },
            properties: {
              name: hole.ID,
              :'marker-color' => '#00607d',
              :'marker-symbol' => 'default_marker',
              :'marker-size' => 'medium'
            }
          }
        end

        respond_with(@geojson)
      end

      def show
        @hole = Hole.find(params[:id])
      end

      def new
        @hole = Hole.new
      end

      def edit
        @hole = Hole.find(params[:id])
      end

      def create
        @hole = Hole.new(hole_params)

        if @hole.save
          redirect_to holes_path
        else
          render :new
        end
      end

      def update
        @hole = Hole.find(params[:id])

        if @hole.update_attributes(hole_params)
          redirect_to hole_path(@hole)
        else
          render :edit
        end
      end

      def destroy
        @hole = Hole.find(params[:id])
        @hole.destroy
        redirect_to holes_path
      end

      def import
        Hole.import(params[:file])
      end

      protected

      def hole_params
        params.require(:hole).permit(
          :ID, :date, :lat, :lng, :description
        )
      end

    end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  
  before_filter :load_hole

  def new
    @sample = @hole.samples.build
  end

  def create
    @sample = @hole.samples.build(sample_params)

    if @sample.save
      redirect_to @hole, notice: "Sample Log created successfully"
    else
      render :new
    end
  end

  def destroy
  end

  protected

  def load_hole
    @hole = Hole.find(params[:hole_id])
  end

  def sample_params
    params.require(:sample).permit(:from, :to, :rock_type, :discharge, :gold, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drill_logs_helper.rb
module DrillLogsHelper
end

app/helpers/holes_helper.rb
module HolesHelper
   def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/drill_logs/create.html.erb
<h1>DrillLogs#create</h1>
<p>Find me in app/views/drill_logs/create.html.erb</p>

app/views/drill_logs/destroy.html.erb
<h1>DrillLogs#destroy</h1>
<p>Find me in app/views/drill_logs/destroy.html.erb</p>

app/views/drill_logs/new.html.erb
    <%= link_to "Back to hole", hole_path(@hole) %><br/>

    <h2>Write a drill_log for <em><%= @hole.ID %></em>.</h2>

    <%= form_for([@hole, @drill_log]) do |f| %>
      <% if @drill_log.errors.any? %>
        <div>
          <%= pluralize(@drill_log.errors.count, "error") %> prevented the drill_log from being saved:
          <ul>
            <% @drill_log.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= f.label :from %><br>
        <%= f.number_field :from  %>
      </div>
      <div>
        <%= f.label :to %><br>
        <%= f.number_field :to  %>
      </div>
      <div>
        <%= f.label :num_pails %><br>
        <%= f.number_field :num_pails  %>
      </div>
      <div>
        <%= f.label :rock_type %><br>
        <%= f.text_field :rock_type %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>

app/views/holes/_form.html.erb
    <%= form_for @hole do |f| %>
      <% if @hole.errors.any? %>
        <div>
          <%= pluralize(@hole.errors.count, "error") %> prevented this hole from being submitted:
          <ul>
            <% @hole.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.label :ID %><br>
        <%= f.text_field :ID %>
      </div>
      <div>
        <%= f.label :date %><br>
        <%= f.date_field :date %>
      </div>
      <div>
        <%= f.label :lat %><br>
        <%= f.number_field :lat, :step => 'any' %>
        
      </div>
      <div>
        <%= f.label :lng %><br>
        <%= f.number_field :lng, :step => 'any' %>
      </div>
      <div>
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>
      <div>
        <%= f.submit "Submit" %> 
      </div>
    <% end %>

app/views/holes/edit.html.erb
    <%= link_to "Back to all holes", holes_path %>

    <h2>Edit this hole!</h2>
    <%= render 'form' %>

app/views/holes/index.html.erb
<div class="col-sm-12 background-image-home"> 
  <div class="jumbotron">
    <div class="container">
      <div class="row row-centered">
       <h1>Hayes Creek Drilling 2016</h1>
        <div>
        <p>
          This is the drill logs site</p>
          <p><a class="btn btn-primary btn-lg" href="new_hole_path" role="button">Add a hole!</a>
          <select name="city_id" id="city_id">
            <% holes_array = @holes.map { |city| [city.ID, city.lat] } %>
            <%= options_for_select(holes_array) %>
          </select>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
    <hr>
    <% @holes.each do |hole| %>
      <h2>Hole: <%= link_to hole.ID, hole_path(hole) %></h2>
      <h3>Drilled on: <%= formatted_date(hole.date) %></h3>
      <p><%= hole.description %></p>
      <p>Coordinates: <%= hole.lat %>, <%= hole.lng %></p>
      <hr>

      <%= form_tag holes_path, multipart: true do %>
<% end %>
    <% end %>

app/views/holes/new.html.erb
    <%= link_to "Back to all holes", holes_path %>

    <h2>Submit a hole!</h2>
    <%= render 'form' %>

app/views/holes/show.html.erb
<div class="container">
    <%= link_to "Back to all holes", holes_path %><br/>
    <div id='map'></div>

    <%= javascript_tag do %>
      lat = '<%= @hole.lat %>';
      lng = '<%= @hole.lng %>';
    <% end %>

    <h2>Hole: <%= link_to @hole.ID, hole_path(@hole) %></h2>
      <h3>Drilled on: <%= formatted_date(@hole.date) %></h3>
      <p><%= @hole.description %></p>
      <p>Coordinates: <%= @hole.lat %>, <%= @hole.lng %></p>
      <div class="row">
        <h3> Drill Log </h3>
        <div class = "table-responsive col-md-4">
          <table class = "table table-hover">
            <tr>
              <th>From (ft)</th>
              <th>To (ft)</th>
              <th># of Pails</th>
              <th>Type of Rock</th>
            </tr>
            <% @hole.drill_logs.each do |drill_log| %>
              <tr>
                <td><%= drill_log.from %></td>
                <td><%= drill_log.to %></td>
                <td><%= drill_log.num_pails %></td>
                <td><%= drill_log.rock_type %></td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
      <p><%= link_to "Write a drill_log!", new_hole_drill_log_path(@hole) %></p>

      <div class="row">
        <h3> Sample Log </h3>
        <div class = "table-responsive col-md-4">
          <table class = "table table-hover">
            <tr>
              <th>From (ft)</th>
              <th>To (ft)</th>
              <th>Type of Rock</th>
            </tr>
            <% @hole.samples.each do |sample| %>
              <tr>
                <td><%= sample.from %></td>
                <td><%= sample.to %></td>
                <td><%= sample.rock_type %></td>
              </tr>
            <% end %>
          </table>
                <p><%= link_to "Write a sample log!", new_hole_sample_path(@hole) %></p>
        </div>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DrillLogs</title>
<!--   <link rel='stylesheet', href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.15.0/mapbox-gl.css'/> -->
   <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<!--   <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.15.0/mapbox-gl.js'/> -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/samples/edit.html.erb
<h1>Samples#edit</h1>
<p>Find me in app/views/samples/edit.html.erb</p>

app/views/samples/new.html.erb
    <%= link_to "Back to hole", hole_path(@hole) %><br/>

    <h2>Write a sample for <em><%= @hole.ID %></em>.</h2>

    <%= form_for([@hole, @sample]) do |f| %>
      <% if @sample.errors.any? %>
        <div>
          <%= pluralize(@sample.errors.count, "error") %> prevented the sample from being saved:
          <ul>
            <% @sample.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= f.label :from %><br>
        <%= f.number_field :from  %>
      </div>
      <div>
        <%= f.label :to %><br>
        <%= f.number_field :to  %>
      </div>
      <div>
        <%= f.label :rock_type %><br>
        <%= f.text_field :rock_type %>
      </div>
      <div>
        <%= f.label :discharge %><br>
        <%= f.number_field :discharge %>
      </div>
      <div>
        <%= f.label :gold %><br>
        <%= f.text_field :gold %>
      </div>
      <div>
        <%= f.label :notes %><br>
        <%= f.text_field :notes %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>